import Head from 'next/head'
import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Agent Chat UI',
  description: 'generated by shabdsnuti@outlook.com',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
      <html lang="en">
        <Head>
          <meta charSet='utf-8' />
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link href="https://cdn.tailwindcss.com" rel="stylesheet" />
        </Head>  
        <body className="h-screen overflow-hidden flex items-center justify-center" style={{background: '#edf2f7'}}>{children}</body>
      </html>
    )
}